on: [push, pull_request]

jobs:
  evaluator:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: instalando as dependências
          run: npm install
        - uses: actions/checkout@v2
      
        - name: instalando as dependências
          run: npm run test:functional
