on: [push, pull_request]

jobs:
  evaluator:
    name: Evaluator Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: instalando as dependências
        run: npm run test:functional
